language: ruby
env:
  global:
    - CC_TEST_REPORTER_ID=f9b0826de168f69b05173435db121ac7434569bd099e610967ede64323c42572

script: bundle exec rspec

before_script:
  - ./cc-test-reporter before-build
after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter format-coverage -t simplecov -o ./coverage/codeclimate.$CI_NODE_INDEX.json ./coverage/.resultset.json; fi
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter sum-coverage --output - --parts $CI_NODE_TOTAL coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --input -; fi
